swagger: "2.0"
info:
  description: "API-dokumentation för systemregister.sundsvall.se"
  version: "v0"
  title: "Systemregister API-dokumentation"
  contact:
    email: "TODO@sundsvall.se"
basePath: "/api/v0/"
paths:
  /it-service/{uuid}:
    get:
      tags:
      - "IT-stöd"
      summary: "Hämta ett IT-stöd"
      description: "Hämtar ett IT-stöd"
      produces:
      - "application/json"
      parameters:
      - name: "uuid"
        in: "path"
        description: "IT-stödets unika ID (uuid)"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/ITService"
        "404":
          description: "IT-stödet kunde inte hittas"
  /it-service:
    get:
      tags:
      - "IT-stöd"
      summary: "Hämta samtliga IT-stöd"
      description: "Hämtar samtliga IT-stöd"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/ITServiceList"
        "404":
          description: "Hittade inga IT-stöd"     
definitions:
  ITService:
    type: "object"
    properties:
      uuid:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      systemCategory:
        $ref: "#/definitions/SystemCategory"
      objectNumber:
        type: "integer"
      management:
        $ref: "#/definitions/Management"
      systemOwner:
        $ref: "#/definitions/SystemOwner"
      assistantOwner:
        $ref: "#/definitions/AssistantOwner"  
      systemManager:
        $ref: "#/definitions/SystemManager"
      operations:
        type: "string"
      businessCritical:
        type: "string"
        
  SystemCategory:
    type: "object"
    properties:
      name: 
        type: "string"
      objectIntervalStart:
        type: "integer"
      objectIntervalEnd:
        type: "integer"
      objectGroup:
        type: "integer"
      objectArea:
        type: "integer"
      
  
  Management:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        
  SystemOwner:
    type: "object"
    properties:
      username:
        type: "string"
      firstName:
        type: "string"      
      lastName:  
        type: "string"
      mail:
        type: "string"
        
  AssistantOwner:
    type: "object"
    properties:
      username:
        type: "string"
      firstName:
        type: "string"      
      lastName:  
        type: "string"
      mail:
        type: "string"      
        
  SystemManager:
    type: "object"
    properties:
      username:
        type: "string"
      firstName:
        type: "string"      
      lastName:  
        type: "string"
      mail:
        type: "string"
        
  ITServiceList:
    type: "array"
    items:
      $ref: "#/definitions/ITService"