swagger: "2.0"
info:
  description: "API documentation for systemregister.sundsvall.se"
  version: "v0"
  title: "Systemregister API documentation"
  contact:
    email: "TODO@sundsvall.se"
basePath: "/api/v0/"
paths:
  /it-service/{uuid}:
    get:
      tags:
      - "IT-service"
      summary: "Retrieve one IT-service"
      description: "Retrieves one IT-service"
      produces:
      - "application/json"
      parameters:
      - name: "uuid"
        in: "path"
        description: "The unique indentifier of the IT-service"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/ITService"
        "404":
          description: "An IT-service with a matching uuid could not be found"
  /it-service:
    get:
      tags:
      - "IT-service"
      summary: "Retrieve all IT-services"
      description: "Retrieves all IT-services"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/ITServiceList"
        "404":
          description: "No IT-services found"
definitions:
  ITService:
    type: "object"
    properties:
      uuid:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      systemCategory:
        $ref: "#/definitions/SystemCategory"
      function:
        type: "string"
      objectNumber:
        type: "integer"
      management:
        $ref: "#/definitions/Management"
      systemOwner:
        $ref: "#/definitions/SystemOwner"
      assistantOwner:
        $ref: "#/definitions/AssistantOwner"  
      systemManager:
        $ref: "#/definitions/SystemManager"
      operations:
        type: "string"
      businessCritical:
        type: "string"
      securityOfInformationClassified:
        type: "string"
      containsPersonalInformation:
        type: "string"
      documentedInPulregister:
        type: "string"
      lifeCycleStatus:
        type: "string"
      endOfLifeDate:
        type: "string"
      endOfLifeComment:
        type: "string"
      systemInUse:
        type: "string"
      systemInUseComment:
        type: "string"
      systemHealth:
        type: "string"
      systemHealthComment:
        type: "string"
      agreementExists:
        type: "string"
      agreementExpiration:
        type: "string"
      agreementComment:
        type: "string"
      supportExists:
        type: "string"
      supportExpiration:
        type: "string"
      supportComment:
        type: "string"
      managementCost:
        type: "integer"
      developmentCost:
        type: "integer"
      totalCost:
        type: "integer"
      comment:
        type: "string"
      objectUpdated:
        type: "string"
        
  SystemCategory:
    type: "object"
    properties:
      name: 
        type: "string"
      objectIntervalStart:
        type: "integer"
      objectIntervalEnd:
        type: "integer"
      objectGroup:
        type: "integer"
      objectArea:
        type: "integer"
      
  
  Management:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        
  SystemOwner:
    type: "object"
    properties:
      username:
        type: "string"
      firstName:
        type: "string"      
      lastName:  
        type: "string"
      mail:
        type: "string"
        
  AssistantOwner:
    type: "object"
    properties:
      username:
        type: "string"
      firstName:
        type: "string"      
      lastName:  
        type: "string"
      mail:
        type: "string"      
        
  SystemManager:
    type: "object"
    properties:
      username:
        type: "string"
      firstName:
        type: "string"      
      lastName:  
        type: "string"
      mail:
        type: "string"
        
  ITServiceList:
    type: "array"
    items:
      $ref: "#/definitions/ITService"